- name: Create All RoboShop Parameters
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameters_store:
        name: "param.dev.catlogue.MONGO"
        value: "false"
        region: "us-east-1"