- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include Download App Code Tasks From Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

