- name: Add RoboShop Application User
  when: APP_USER is defined
  ansible.builtin.user:
    name: " {{ APP_USER }}"

- name: Remove Previous Version of App
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

- name: Download App Content & Extract it
  ansible.builtin.unarchive:
    src: https://github.com/nawaz990/{{COMPONENT}}/archive/refs/heads/main.zip
    dest: "/tmp"
    remote_src: yes

- name: Copy Extracted App Content to App Location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: "{{ APP_LOC }}"
    remote_src: yes